#!/bin/bash

python buildWZworkspace_forZZ_1sigma_allErrOK_withEWKSyst_signalShapeFix_f5g_ifLessThen1SetTo1_2604Files_SMaTGCfit_SMZZasBKG_CLsUnc.py --config=config_ZZ_Zlldata_withSherpaSyst_withEWKSyst_binBYbin_SMZZasbkg_asSM_7and8TeV

combineCards.py wv_semil_ch1_smzzasbkgboosted.txt > wv_semil_ZZ2l2nu_2604Files_allUnc_CLsUnc_SMZZasBKG_f5g_single.txt

text2workspace.py -m 126 wv_semil_ZZ2l2nu_2604Files_allUnc_CLsUnc_SMZZasBKG_f5g_single.txt -o Example_ZZ2l2nu_f5g_2604Files_SMaTGCfit_7and8TeV_allUnc_CLsUnc_SMZZasBKG_single.root -P CombinedEWKAnalysis.CommonTools.HagiwaraAndZeppenfeldTwoDimensionalModel_wz_f5g_ifLessThen1SetTo1_2604files_SMaTGCfit_SMZZasBKG_CLsUnc:dkglZModel_wz_f5g_ifLessThen1SetTo1_2604files_SMaTGCfit_SMZZasBKG_CLsUnc --PO channels=ch1_smzzasbkg --PO range_lZ=-0.008,0.008 --PO range_dkg=-0.008,0.008
